testname: Internship Experiment
testId: lss_lms
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php

pages:
  - type: likert_multi_stimulus
    id: lms2
    name: Score
    content: Rate the samples !
    randomize: false
    showConditionNames: false
    stimuli:
      C1: configs/resources/audio/mono_c1.wav
      C2: configs/resources/audio/mono_c2.wav

    response:
      - value: bad
        label: Bad
        img: configs/resources/images/star_off.png
        imgSelected: configs/resources/images/star_on.png
        imgHigherResponseSelected: configs/resources/images/star_on.png
      - value: poor
        label: Poor
        img: configs/resources/images/star_off.png
        imgSelected: configs/resources/images/star_on.png
        imgHigherResponseSelected: configs/resources/images/star_on.png
      - value: fair
        label: Fair
        img: configs/resources/images/star_off.png
        imgSelected: configs/resources/images/star_on.png
        imgHigherResponseSelected: configs/resources/images/star_on.png
      - value: good
        label: Good
        img: configs/resources/images/star_off.png
        imgSelected: configs/resources/images/star_on.png
        imgHigherResponseSelected: configs/resources/images/star_on.png
      - value: excellent
        label: Excellent
        img: configs/resources/images/star_off.png
        imgSelected: configs/resources/images/star_on.png
        imgHigherResponseSelected: configs/resources/images/star_on.png

  - type: finish
    name: Thank you
    content: Thank you for attending
    popupContent: Your results were sent. Goodbye and have a nice day
    showResults: true
    writeResults: true
    questionnaire:
      - type: number
        label: Age
        name: age
        min: 0
        max: 100
        default: 30
      - type: likert
        name: from
        label: How have you heard about this experiment?
        response:
          - value: networks
            label: Social Networks
          - value: work
            label: Work
          - value: link
            label: Direct Link

      - type: likert
        name: caract
        label: How
        response:
          - value: pro
            label: Professional Musician
          - value: amateur
            label: Amateur Musician
          - value: worker
            label: Work in Audio field
          - value: other
            label: Other
